export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const CLEAR_VERSION_HISTORY = 'CLEAR_VERSION_HISTORY';
export const LOADED_VERSION_HISTORY = 'LOADED_VERSION_HISTORY';
export const LOADED_VERSIONS = 'LOADED_VERSIONS';

export const LOADING_VERSION_HISTORY = 'LOADING_VERSION_HISTORY';
export const LOADING_VERSIONS = 'LOADING_VERSIONS';


