export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_VERSION_HISTORY = 'LOAD_VERSION_HISTORY';
export const LOADED_VERSIONS = 'LOADED_VERSIONS';

